version: '3.8'

# services:

  
      

# volumes:
#   postgres_data:

services:
  database:
    image: postgres:15-alpine

    container_name: postgres_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: games

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: DockerFile

  #   ports:
  #     - "8000:8000"

  #   depends_on:
  #     - database

  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data: