from collections.abc import Sequence
from typing import AsyncContextManager, Protocol

from app.application.dto import Game, GameRecommendation
from app.domain.enums import GameCategory, GameCategoryValue, GameSort


class GameRepository(Protocol):
    async def insert_games(self, games: Sequence[Game]) -> None: ...
    async def get_by_id(self, game_id: int) -> Game | None: ...
    async def get_by_slug(self, slug: str) -> Game | None: ...
    async def replace_recommendations(
        self, recommendations: Sequence[GameRecommendation]
    ) -> None: ...
    async def get_recommendations(self, game_id: int, limit: int) -> list[Game]: ...
    async def get_games_by_category(
        self, category: GameCategory, value: str, offset: int, limit: int
    ) -> list[Game]: ...
    async def search(self, title: str, limit: int, offset: int) -> list[Game]: ...
    async def get_most_popular(self, limit: int) -> list[Game]: ...
    async def get_category_values(self, category: GameCategoryValue) -> list[str]: ...
    async def list_games(
        self,
        query: str | None,
        genres: list[str] | None,
        companies: list[str] | None,
        platforms: list[str] | None,
        sort: GameSort,
        offset: int,
        limit: int,
    ) -> tuple[list[Game], int]: ...


class GameRepositoryProvider(Protocol):
    def read(self) -> AsyncContextManager[GameRepository]: ...
    def write(self) -> AsyncContextManager[GameRepository]: ...
