name: Backend CD

on:
  push:
    branches:
      - master

    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yml"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: backend-production
  cancel-in-progress: true

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: ${{ vars.GCP_REGION }}
  GAR_REGION: ${{ vars.GAR_REGION }}
  GAR_REPOSITORY: ${{ vars.GAR_REPOSITORY }}
  CLOUD_RUN_SERVICE: ${{ vars.CLOUD_RUN_SERVICE }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      # ------------------------------------------
      # Autenticação Google Cloud
      # ------------------------------------------

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      # ------------------------------------------
      # Artifact Registry
      # ------------------------------------------

      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker \
            ${{ env.GAR_REGION }}-docker.pkg.dev \
            --quiet

      # ------------------------------------------
      # Build
      # ------------------------------------------

      - name: Build Docker image
        run: |
          docker build \
            -f ./backend/Dockerfile \
            -t "${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" \
            ./backend

      # ------------------------------------------
      # Push
      # ------------------------------------------

      - name: Push Docker image
        run: |
          docker push \
            "${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      # ------------------------------------------
      # Deploy
      # ------------------------------------------

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          region: ${{ env.REGION }}
          service: ${{ env.CLOUD_RUN_SERVICE }}
          image: ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Show service URL
        run: |
          echo "${{ steps.deploy.outputs.url }}"
